[project]
name = "familiar"
version = "0.0.1"
requires-python = ">=3.13.5"
readme = "README.md"
license = "MIT"
dependencies = [
    "pyglet~=2.0.10"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"